model:
  vocab_size: 128256
  hidden_size: 2048
  intermediate_size: 8192
  num_hidden_layers: 16
  num_attention_heads: 32
  num_key_value_heads: 8
  max_position_embeddings: 4096
  _attn_implementation: flash_attention_2
  bos_token_id: 128000
  eos_token_id: 128001
trainer:
  output_dir: checkpoints/debug
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 4e-3
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1e-15
  num_train_epochs: 1
  max_steps: 200000
  lr_scheduler_type: cosine_with_min_lr
  lr_scheduler_kwargs:
    min_lr: 0
  warmup_steps: 1000
  logging_steps: 1
  save_steps: 10000
  seed: 42
  bf16: true
  deepspeed: /wang_ssd/yifeizuo/PretrainHub/recipes/deepspeed/zero3.json
  optim: adamw_torch_fused
  report_to: wandb
  run_name: debug
  resume_from_checkpoint: null
  hub_model_id: null
  hub_strategy: end
task:
  tokenizer_name: meta-llama/Meta-Llama-3-8B
  sequence_length: 4096
  dataset:
    path: mlfoundations/dclm-baseline-1.0
    split: train
    streaming: true

